# Generated by Django 2.1.7 on 2019-04-11 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_follower'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follower',
            old_name='followee',
            new_name='being_followed',
        ),
    ]
