# Generated by Django 2.1.7 on 2019-04-11 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190411_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follower',
            name='being_followed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='being_followeds', to=settings.AUTH_USER_MODEL),
        ),
    ]
