# Generated by Django 2.1.7 on 2019-04-02 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_auto_20190402_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='modelimage',
            field=models.ImageField(upload_to='post_images'),
        ),
    ]
