# Generated by Django 2.1.7 on 2019-03-31 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_postimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postimage',
            old_name='image',
            new_name='modelimage',
        ),
    ]
