# Generated by Django 2.1.7 on 2019-04-06 22:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0010_auto_20190406_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
